version: '2.0'

services:

  # dht22-db:
  #   image: ambientum/mysql:5.7
  #   container_name: dht22-db
  #   ports:
  #     - "3310:3306"
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=dht22-db
  #     - MYSQL_PASSWORD=dht22-db
  #     - MYSQL_DATABASE=dht22-db
  #     - MYSQL_USER=dht22-db
  #   restart: always
      
  dht22-api:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: dht22-db/api
    container_name: dht22-api
    command: ["pm2-runtime", "src/index.js"]
    working_dir: /home/node/
    ports:
      - 8300:3000
    restart: always